### ISSUE TITLE
Limited Number of accordions?

### ISSUE THREAD

**Issue by smc-pt** [anvk/a11yAccordion#44]
Thanks for posting this accessible accordion. I've been testing it and it's working. I've even styled it to match our organizations look and feel without any problems. However, now that I've done my tests, I've attempted to apply with actual content. 

I've been using Voiceover on a Mac to test and everything works fine until I add more than 10 or 12 list items, and then things start to fall apart. 

After that, the "Show/Hide" buttons open and close the accordion, but the "control/option/right arrow" starts to skip the "a11yaccordionHideArea" content and jumps to the "a11yAccordionItemHeader" - the only way I've been able to get it to work again is to surround my "a11yAccordionItemHeader" titles with h2 heading tags, and list them using the "control/option/u" command to list the headings and jumping to the heading I need. But even then the "Show/Hide" button doesn't work, I have to click on the h2 title to open the accordion. 

Is there a limit on how many accordion items can be used? 

Here something else that may also be a factor: 
I am implementing this into a SharePoint Content Management System. 

Is there a problem using this script with Content Management Systems? 

Thank you for your help.

**Comment by anvk** [comment]
Hi @smc-pt ,
I'm glad to hear that my accordion could be of help in your project. I will try to reproduce the issue you've reported. Quiet honestly not sure why this issue happening to you since this accordion uses a pretty simple HTML structure which should work no matter how many items are within. I definitely did not notice any limitations on the number of items.

I wonder if you have some "problematic" content in one of the accordion items which causes this behavior. OR just like you've mentioned, there is something odd related to the CMS you are using. To be honest I have not tried to use my accordion in CMS before but I know other people who used accordion+CMS without a problem.

- One of the good potential tests would be to increase number of items in the basic example I provided in the GitHub repo and see if it breaks accordion. I will do this test myself as well.

- Another good test is to extend the basic example with the content you are using on your production and see if it breaks anything. Theoretically the example is pretty bare bones HTML and if you change accordion to be the same as in the project you are working with you should be able to observe the same error... if any.

**Comment by smc-pt** [comment]
Hi @anvk, 

Thanks for the response. 

I have a feeling it's a SharePoint issue. The code inside the "a11yAccordionHideArea" div is a simple paragraph. Nothing fancy. And I was adding list items one at a time. Everything worked fine until I added the 10th item. Then it all fell apart. 

It seems to work locally, or on a separate server, although the show/hide items don't display. 

I'll continue to experiment.
